In [1]:
#Import the libraries
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=pd.read_csv('EastWestAirlines1.csv')
data.head()

ID#  Balance  Qual_miles  cc1_miles  cc2_miles  cc3_miles  Bonus_miles  \
0    1    28143           0          1          1          1          174   
1    2    19244           0          1          1          1          215   
2    3    41354           0          1          1          1         4123   
3    4    14776           0          1          1          1          500   
4    5    97752           0          4          1          1        43300   

   Bonus_trans  Flight_miles_12mo  Flight_trans_12  Days_since_enroll  Award?  
0            1                  0                0               7000       0  
1            2                  0                0               6968       0  
2            4                  0                0               7034       0  
3            1                  0                0               6952       0  
4           26               2077                4               6935       1

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3999 entries, 0 to 3998
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID#                3999 non-null   int64
 1   Balance            3999 non-null   int64
 2   Qual_miles         3999 non-null   int64
 3   cc1_miles          3999 non-null   int64
 4   cc2_miles          3999 non-null   int64
 5   cc3_miles          3999 non-null   int64
 6   Bonus_miles        3999 non-null   int64
 7   Bonus_trans        3999 non-null   int64
 8   Flight_miles_12mo  3999 non-null   int64
 9   Flight_trans_12    3999 non-null   int64
 10  Days_since_enroll  3999 non-null   int64
 11  Award?             3999 non-null   int64
dtypes: int64(12)
memory usage: 375.0 KB


In [7]:
data=data.iloc[:,1:]
data.head()

cc1_miles  cc2_miles  cc3_miles  Bonus_miles  Bonus_trans  \
0          1          1          1          174            1   
1          1          1          1          215            2   
2          1          1          1         4123            4   
3          1          1          1          500            1   
4          4          1          1        43300           26   

   Flight_miles_12mo  Flight_trans_12  Days_since_enroll  Award?  
0                  0                0               7000       0  
1                  0                0               6968       0  
2                  0                0               7034       0  
3                  0                0               6952       0  
4               2077                4               6935       1

In [8]:
array=data.values

In [10]:
array

array([[   1,    1,    1, ...,    0, 7000,    0],
       [   1,    1,    1, ...,    0, 6968,    0],
       [   1,    1,    1, ...,    0, 7034,    0],
       ...,
       [   3,    1,    1, ...,    0, 1402,    1],
       [   1,    1,    1, ...,    1, 1401,    0],
       [   1,    1,    1, ...,    0, 1398,    0]], dtype=int64)

In [11]:
stscaler=StandardScaler().fit(array)
X=stscaler.transform(array)

In [12]:
X

array([[-0.76957841, -0.09824189, -0.06276658, ..., -0.36216787,
         1.39545434, -0.7669193 ],
       [-0.76957841, -0.09824189, -0.06276658, ..., -0.36216787,
         1.37995704, -0.7669193 ],
       [-0.76957841, -0.09824189, -0.06276658, ..., -0.36216787,
         1.41192021, -0.7669193 ],
       ...,
       [ 0.68312117, -0.09824189, -0.06276658, ..., -0.36216787,
        -1.31560393,  1.30391816],
       [-0.76957841, -0.09824189, -0.06276658, ..., -0.09850333,
        -1.31608822, -0.7669193 ],
       [-0.76957841, -0.09824189, -0.06276658, ..., -0.36216787,
        -1.31754109, -0.7669193 ]])

In [13]:
dbscan=DBSCAN(eps=1.5,min_samples=10)
dbscan.fit(X)

DBSCAN(eps=1.5, min_samples=10)

In [14]:
dbscan.labels_

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [16]:
c1=pd.DataFrame(dbscan.labels_,columns=['cluster'])
c1

cluster
0           0
1           0
2           0
3           0
4           1
...       ...
3994        1
3995        1
3996        1
3997        0
3998        0

[3999 rows x 1 columns]

In [21]:
data=pd.concat([data,c1],axis=1)
data

cc1_miles  cc2_miles  cc3_miles  Bonus_miles  Bonus_trans  \
0             1          1          1          174            1   
1             1          1          1          215            2   
2             1          1          1         4123            4   
3             1          1          1          500            1   
4             4          1          1        43300           26   
...         ...        ...        ...          ...          ...   
3994          1          1          1         8525            4   
3995          1          1          1          981            5   
3996          3          1          1        25447            8   
3997          1          1          1          500            1   
3998          1          1          1            0            0   

      Flight_miles_12mo  Flight_trans_12  Days_since_enroll  Award?  cluster  \
0                     0                0               7000       0        0   
1                     0                0               6968       0        0   
2                     0                0               7034       0        0   
3                     0                0               6952       0        0   
4                  2077                4               6935       1        1   
...                 ...              ...                ...     ...      ...   
3994                200                1               1403       1        1   
3995                  0                0               1395       1        1   
3996                  0                0               1402       1        1   
3997                500                1               1401       0        0   
3998                  0                0               1398       0        0   

      cluster  cluster  
0           0        0  
1           0        0  
2           0        0  
3           0        0  
4           1        1  
...       ...      ...  
3994        1        1  
3995        1        1  
3996        1        1  
3997        0        0  
3998        0        0  

[3999 rows x 12 columns]